<div id="pf212" class="pf w0 h0" data-page-no="212"><div class="pc pc212 w0 h0"><img class="bi x13 y5 w2 ha" alt="" src="bg212.png"/><div class="t m0 xd h9 y75 ff1 fs3 fc0 sc0 lsb">《<span class="ff2 ls0 wsce">Python Co<span class="_ _6"></span>okb<span class="_ _6"></span>o<span class="_ _6"></span>ok</span><span class="ls0 wsa0">》第三版<span class="ff2 wsce">, Release 2.0.0</span></span></div><div class="t m0 x5 hd y112 ff2 fs4 fc4 sc0 ls0 ws211">16.3<span class="_ _e"> </span>14.3 <span class="ff1">在单元测试中测试异常情况</span></div><div class="t m0 x5 he y113 ff2 fs2 fc4 sc0 ls0 ws212">16.3.1 <span class="ff1">问题</span></div><div class="t m0 x0 h9 y3213 ff1 fs3 fc0 sc0 ls0">你想写个测试用例来准确的判断某个异常是否被抛出。</div><div class="t m0 x5 he y3214 ff2 fs2 fc4 sc0 ls0 ws212">16.3.2 <span class="ff1">解决方案</span></div><div class="t m0 x0 h9 yae2 ff1 fs3 fc0 sc0 ls2c ws129e">对于异常的测试可使用 <span class="ff6 ls0 wse7b">assertRaises() </span><span class="ws12f">方法。例如，如果你想测试某个函数抛出<span class="_ _1"></span></span></div><div class="t m0 x5 h9 y3215 ff1 fs3 fc0 sc0 ls4">了<span class="ff6 ls0 ws17c">ValueError <span class="ff1">异常，像下面这样写：</span></span></div><div class="t m0 x5 h10 y3381 ff7 fs5 fca sc0 ls0 ws146">import <span class="fcc">unittest</span></div><div class="t m0 x5 h11 y3382 ffa fs5 fcd sc0 ls0 ws4"># A simple function to illustrate</div><div class="t m0 x5 hf y3383 ff7 fs5 fca sc0 ls0 ws139">def <span class="ff8 fcb ws13a">parse_int<span class="fc0">(s):</span></span></div><div class="t m0 x15 hf y3384 ff7 fs5 fca sc0 ls0 ws146">return <span class="ff8 ws13a">int<span class="fc0">(s)</span></span></div><div class="t m0 x5 hf y3385 ff7 fs5 fca sc0 ls0 ws16a">class <span class="fcc ws156">TestConversion<span class="ff8 fc0 ws13a">(unittest<span class="fc6 ls34">.</span>TestCase):</span></span></div><div class="t m0 x15 hf y3386 ff7 fs5 fca sc0 ls0 ws139">def <span class="ff8 fcb ws13a">test_bad_int<span class="fc0">(<span class="fca">self</span>):</span></span></div><div class="t m0 x16 hf y3387 ff8 fs5 fca sc0 ls0 ws13a">self<span class="fc6">.<span class="fc0">assertRaises(</span></span>ValueError<span class="fc0 ws4">, parse_int, <span class="ff9 fc9 ws13b">&apos;</span></span><span class="fc9">N/A<span class="ff9 ws13b">&apos;</span><span class="fc0">)</span></span></div><div class="t m0 x0 h9 y3388 ff1 fs3 fc0 sc0 ls0">如果你想测试异常的具体值，需要用到另外一种方法：</div><div class="t m0 x5 h10 y3389 ff7 fs5 fca sc0 ls0 ws146">import <span class="fcc">errno</span></div><div class="t m0 x5 hf y338a ff7 fs5 fca sc0 ls0 ws16a">class <span class="fcc ws156">TestIO<span class="ff8 fc0 ws13a">(unittest<span class="fc6 ls34">.</span>TestCase):</span></span></div><div class="t m0 x15 hf y338b ff7 fs5 fca sc0 ls0 ws139">def <span class="ff8 fcb ws13a">test_file_not_found<span class="fc0">(<span class="fca">self</span>):</span></span></div><div class="t m0 x16 hf y2e88 ff7 fs5 fca sc0 ls0 ws156">try<span class="ff8 fc0">:</span></div><div class="t m0 x17 hf y2e89 ff8 fs5 fc0 sc0 ls32">f<span class="fc6 ls33">=<span class="fca ls0 ws13a">open<span class="fc0">(<span class="ff9 fc9 ls34">&apos;</span><span class="fc9">/file/not/found<span class="ff9 ls34">&apos;</span></span>)</span></span></span></div><div class="t m0 x16 hf y338c ff7 fs5 fca sc0 ls0 ws146">except <span class="ff8 ws155">IOError </span><span class="ws157">as <span class="ff8 fc0">e:</span></span></div><div class="t m0 x17 hf y338d ff8 fs5 fca sc0 ls0 ws13a">self<span class="fc6">.<span class="fc0">assertEqual(e</span><span class="ls34">.</span><span class="fc0 ws13b">errno, errno</span><span class="ls34">.</span><span class="fc0">ENOENT)</span></span></div><div class="t m0 x16 hf y338e ff7 fs5 fca sc0 ls0 ws156">else<span class="ff8 fc0">:</span></div><div class="t m0 x17 hf y338f ff8 fs5 fca sc0 ls0 ws13a">self<span class="fc6">.<span class="fc0">fail(<span class="ff9 fc9 ls34">&apos;</span><span class="fc9 ws13b">IOError not raised<span class="ff9 ls34">&apos;</span></span>)</span></span></div><div class="t m0 x5 he y3390 ff2 fs2 fc4 sc0 ls0 ws212">16.3.3 <span class="ff1">讨论</span></div><div class="t m0 x0 h9 y3391 ff6 fs3 fc0 sc0 ls0 ws129f">assertRaises() <span class="ff1 ls10 wsdf">方法为测试异常存在性提供了一个简便方法<span class="_ _1"></span>。一个常见的陷阱是</span></div><div class="t m0 x5 h9 y1a91 ff1 fs3 fc0 sc0 ls0">手动去进行异常检测。比如：</div><div class="t m0 x5 hf y3392 ff7 fs5 fca sc0 ls0 ws16a">class <span class="fcc ws156">TestConversion<span class="ff8 fc0 ws13a">(unittest<span class="fc6 ls34">.</span>TestCase):</span></span></div><div class="t m0 x15 hf y3393 ff7 fs5 fca sc0 ls0 ws139">def <span class="ff8 fcb ws13a">test_bad_int<span class="fc0">(<span class="fca">self</span>):</span></span></div><div class="t m0 x16 hf y3394 ff7 fs5 fca sc0 ls0 ws156">try<span class="ff8 fc0">:</span></div><div class="t m0 x17 hf y3395 ff8 fs5 fc0 sc0 ls32">r<span class="fc6 ls33">=</span><span class="ls0 ws13a">parse_int(<span class="ff9 fc9 ls34">&apos;</span><span class="fc9">N/A<span class="ff9 ls34">&apos;</span></span>)</span></div><div class="t m0 x16 hf y17ed ff7 fs5 fca sc0 ls0 ws146">except <span class="ff8 ws2a3">ValueError </span><span class="ws157">as <span class="ff8 fc0">e:</span></span></div><div class="t m0 x17 hf y3396 ff8 fs5 fca sc0 ls0 ws13a">self<span class="fc6">.<span class="fc0">assertEqual(</span></span>type<span class="fc0 ws13c">(e), </span>ValueError<span class="fc0">)</span></div><div class="t m0 x5 h9 y29 ff2 fs3 fc0 sc0 ls0 ws21d">16.3.<span class="_ _36"> </span>14.3 <span class="ff1 ws98a">在单元测试中测试异常情况 </span>521</div></div><div class="pi" data-data='{"ctm":[1.500000,0.000000,0.000000,1.500000,0.000000,0.000000]}'></div></div>
